### ISSUE TITLE
error  :Requested pin doesn't exist in the app

### ISSUE THREAD

**Issue by davleo** [ilcato/homebridge-blynk#14]
Evrething is setpu as indicated, but I always get an error about PIN does't not exist, I tested D1 to D6on switch mode nothing works.
here the the message error

Status: 400
Headers: {"content-type":"text/plain;charset=utf-8","access-control-allow-origin":"*","content-length":"39","connection":"close"}
Response: Requested pin doesn't exist in the app.
Status: 400
Headers: {"content-type":"text/plain;charset=utf-8","access-control-allow-origin":"*","content-length":"39","connection":"close"}
Response: Requested pin doesn't exist in the app.
undefined:1
Requested pin doesn't exist in the app.
^

SyntaxError: Unexpected token R in JSON at position 0
    at Object.parse (native)
    at Request._callback (/opt/node/lib/node_modules/homebridge-blynk/index.js:248:43)
    at Request.self.callback (/opt/node/lib/node_modules/homebridge-blynk/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/opt/node/lib/node_modules/homebridge-blynk/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/opt/node/lib/node_modules/homebridge-blynk/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)

**Comment by ilcato** [comment]
Try the new version.
