### ISSUE TITLE
Feature Request: Ability to read Gauge & Display values...

### ISSUE THREAD

**Issue by 0x-Fede** [ilcato/homebridge-blynk#2]
Hi!

Amazing, congratulations!! 

Any guide to add new types of "accessories" from Blynk and read their values?

Thanks!

**Comment by ilcato** [comment]
Working on it

**Comment by 0x-Fede** [comment]
Solved: Root install - Thanks, i updated but some errors found... Can you help me ??

## Update:

[Blynk] Found: SwitchD5
[Blynk] Found: ContactSensor1
[Blynk] Found: TemperatureSensor1
[Blynk] Initializing platform accessory 'SwitchD5'...
[Blynk] Initializing platform accessory 'ContactSensor1'...
[Blynk] Initializing platform accessory 'TemperatureSensor1'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge
Homebridge is running on port 51826.
Response raw data: W1770066083vw2120.600
Response raw data: W1770066083vw5
Response raw data: W1770066083vw118
Response raw data: W1770066083vw10
Response raw data: W1770066083vw2237.900
Response raw data: W1770066083vw12
Response raw data: W1770066083vw8
Response raw data: W1770066083vw445.0000
Response raw data: W1770066083vw9
Response raw data: W1770066083vw7
Response raw data: W1770066083vw321.100
[Blynk] There was a problem sending hardware read command on: V7
[Blynk] There was a problem sending hardware read command on: V3
[Blynk] There was a problem sending hardware read command on: V3
[Blynk] There was a problem sending hardware read command on: V7

# Old:

ERROR LOADING PLUGIN homebridge-blynk:
Error: Cannot find module 'blynk-app-client'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-blynk/index.js:48:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

#     at Module.require (module.js:367:17)

No plugins found. See the README for information on installing plugins.

## Loaded config.json with 0 accessories and 1 platforms.

Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:88
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Blynk' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:88:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:201:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:42:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:38:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)`

**Comment by ilcato** [comment]
@fgredruello: the plugin is not ready yet. There's a problem in Blynkk server that doesn't allow some function to be performed from the API. I'm waiting for a solution from the Blynkk team that is working on that.

**Comment by 0x-Fede** [comment]
Ok. Thanks!

After some test... it works, but Temperature Sensor doesn't works..

Homebridge is running on port 51826.
Response raw data: W1770066083vw8
Response raw data: W1770066083vw7
Response raw data: W1770066083vw1110
Response raw data: W1770066083vw325.300
Response raw data: W1770066083vw5
Response raw data: W1770066083vw2125
Response raw data: W1770066083vw10
Response raw data: W1770066083vw9
Response raw data: W1770066083vw12
Response raw data: W1770066083vw2229
Response raw data: W1770066083vw438.200
[Blynk] There was a problem sending hardware read command on: V11

**Comment by ilcato** [comment]
Now it should work. Read the release notes.

**Comment by ilcato** [comment]
@fgredruello, were you able to retest it?
