### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-blynk

### ISSUE THREAD

**Issue by blynkkk** [ilcato/homebridge-blynk#3]
Hi, could you please help with solving this issue?

Mac OS, npm v 3.8.5

after installing with 

```
$ sudo npm install -g homebridge-blynk
/usr/local/lib
└── homebridge-blynk@0.1.0 
```

and running `homebridge`

getting this:

```
[4/6/2016, 12:39:58 PM] ====================
[4/6/2016, 12:39:58 PM] ERROR LOADING PLUGIN homebridge-blynk:
[4/6/2016, 12:39:58 PM] Error: Cannot find module 'blynk-app-client'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-blynk/index.js:47:13)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[4/6/2016, 12:39:58 PM] ====================
```

when starting homebridge with your ifttt plugin  - it works ok

**Comment by ilcato** [comment]
@blynkkk Fixed dependencies error. Try to remove and reinstall homebridge-blynk

**Comment by blynkkk** [comment]
@ilcato Thanks! it works now. You did a great job with this integration. If you are able to make a quick tutorial on how to get started - we would be happy to promote it via our channels. Also, please let us know if you need some Blynk 🔋Energy for your experiments - we would be happy to add some to your account. That's the least we can do. 

One question: is it possible to use IFFFT plugin in parallel with Blynk. It's loading, but what should be done with .json files? Can we have multiple? Can't find any homebridge documentaiton on that.

Thanks!

**Comment by ilcato** [comment]
@blynkkk, you can have multiple plugins on the same homebridge server. Just put the different plugin configurations inside a specific { } within the "platform" parameter:
`"platforms": [
        {
            "platform": "blynk",
            ...
        },
        {
            "platform": "IFTTT",
            ...
        }
  ]`
